### ISSUE TITLE
Add RsyncClientCmd back in version 4

### ISSUE THREAD

**Issue by norac89** [backuppc/backuppc#132]
In version 3, RsyncClientCmd allowed bypassing the ssh connection for a localhost backup. With version 4, the RsyncClientCmd has been remove.
The equivalent TarClientCmd is still there in version 4. 

I would suggest to bring back RsyncClientCmd in version 4 to give more flexibility.

**Comment by Karmashkin** [comment]
WebUI -> Edit Config -> CGI -> Ctrl-F "RsyncClientPath"
Perhaps this is what you need?

**Comment by norac89** [comment]
Actually one of my use case involve backing up the localhost on a mounted drive. With the "RsyncClientCmd" of version 3, I am able to remove the ssh connection from the command.
Haven't found a way to do this in version 4.

**Comment by WBTMagnum** [comment]
Same use case here. I ended up creating a local backuppc user for the ssh connection.

**Comment by nauevg** [comment]
@norac89
I configured local backup task (without need of ssh connection) with Xfer method TAR. It worked. You can even use rsync for this task, if you need it.
I think there is some reason to remove parameter from RSYNC method.

**Comment by craigbarratt** [comment]
You can set $Conf{RsyncSshArgs} to a command that simply executes its arguments (like ssh does).  However, rsync adds the host name to whatever you specify in $Conf{RsyncSshArgs}, so unfortunately this doesn't work since the first argument is the host name, and env will give an error:
```
$Conf{RsyncSshArgs} = ['-e', '/usr/bin/env'];    # <- this doesn't work
```
A very bad hack would be to use something like this:
```
$Conf{RsyncSshArgs} = ['-e', '/usr/bin/sudo -p'];
```
(sudo has to be passwordless from the BackupPC user.)  The -p (prompt) option expects an argument to set the password prompt (which is not used).  So it consumes the host name argument appended by rsync, then runs the rest of the command like ssh does.  Bingo - the client rsync gets run locally, with elevated privileges from sudo, without ssh.

An alternative would be to write a short shell/python/perl script instead that does it more cleanly - shifts the first argument off argv, and execs the rest.

**Comment by dbrazziel** [comment]
A working example of $RsyncSshArgs would be helpful. My working $RsyncClientCmd for V3 looks like this:

$Conf{RsyncClientCmd} = '$sshPath -l backuppc $host nice -n 19 sudo $rsyncPath $argList+';

How would that be implemented with the new V4 syntax, i.e. '$Conf{RsyncClientPath}' and '$Conf{RsyncSshArgs}'?

**Comment by vvatikiotis** [comment]
> You can set $Conf{RsyncSshArgs} to a command that simply executes its arguments (like ssh does). However, rsync adds the host name to whatever you specify in $Conf{RsyncSshArgs}, so unfortunately this doesn't work since the first argument is the host name, and env will give an error:
> 
> ```
> $Conf{RsyncSshArgs} = ['-e', '/usr/bin/env'];    # <- this doesn't work
> ```
> 
> A very bad hack would be to use something like this:
> 
> ```
> $Conf{RsyncSshArgs} = ['-e', '/usr/bin/sudo -p'];
> ```
> 
> (sudo has to be passwordless from the BackupPC user.) The -p (prompt) option expects an argument to set the password prompt (which is not used). So it consumes the host name argument appended by rsync, then runs the rest of the command like ssh does. Bingo - the client rsync gets run locally, with elevated privileges from sudo, without ssh.
> 
> An alternative would be to write a short shell/python/perl script instead that does it more cleanly - shifts the first argument off argv, and execs the rest.

This solution doesn't work for BackupPC (4.4.0) plugin for TrueNAS

**Comment by craigbarratt** [comment]
What error do you get?

**Comment by rohusan** [comment]
After months without a local backup I'm trying to solve this issue again. My approach is the "very bad hack":

> $Conf{RsyncSshArgs} = ['-e', '/usr/bin/sudo -p'];

Sudo for user u_backup is passwordless but it's not working. See attached XferLog (only failure)


[backuppc-local-host-error.txt](https://github.com/backuppc/backuppc/files/5788392/backuppc-local-host-error.txt)

**Comment by slowphil** [comment]
> A very bad hack would be to use something like this:
> 
> ```
> $Conf{RsyncSshArgs} = ['-e', '/usr/bin/sudo -p'];
> ```
> 
> (sudo has to be passwordless from the BackupPC user.) The -p (prompt) option expects an argument to set the password prompt (which is not used). So it consumes the host name argument appended by rsync, then runs the rest of the command like ssh does. Bingo - the client rsync gets run locally, with elevated privileges from sudo, without ssh.
> 
> An alternative would be to write a short shell/python/perl script instead that does it more cleanly - shifts the first argument off argv, and execs the rest.

Thanks @craigbarratt, this did the trick for me! However, IMHO this hack should be given in the documentation. As it is, buried here in a closed issue, it's a pain to find how to backup the server itself.

**Comment by haarp** [comment]
Honestly it's rather confusing that `RsyncClientPath` implicitely adds the hostname, instead of having it as a placeholder the user can add.

Craig's sudo trick works, but NOT if you have multiple commands in `RsyncClientPath`. This is on Debian 11 RC2.

I had `RsyncClientPath = /usr/bin/nice -n19 /usr/bin/ionice -c3 /usr/bin/rsync`, `RsyncSshArgs = [-e, /usr/bin/sudo -p]` and a corresponding sudoers NOPASSWD entry for the command. Sudo would consistently ask for the password when BackupPC_dump tries to execute rsync, yet manually executing the EXACTLY SAME command as the backuppc user worked without password!

No idea why this is. It makes no sense. Some weird whitespaces when BackupPC executes the command? :shrug: 

It works with `RsyncClientPath = /usr/bin/rsync` and a corresponding changed sudoers entry. You can instead add the (io)nice to  `RsyncSshArgs = [-e, /usr/bin/nice -n19 /usr/bin/ionice -c3 /usr/bin/sudo -p]`.

**Comment by jgoerzen** [comment]
So there's a common use case here that being unable to override $host makes very difficult.

With a setup of bastion ssh hosts (in which one would use ProxyJump in .ssh/config), it is quite common to ssh to something that is a valid config in .ssh/config but not a known hostname.

In v3, I could achieve this by setting the ClientNameAlias to some valid hostname, and then overriding the ssh command to use the .ssh/config settings.  I suppose I could manually put the settings in the RsyncSshArgs but that's a real pain when it's already defined in .ssh/config for the system.

There is no way I can tell to do this now.  It's not just a problem of ping; it seems if BackupPC can't look up the IP address of a hostname, it refuses to do a backup, period.  And I can't override what $host is passed.

**Comment by jgoerzen** [comment]
I found a workaround: I could set the NMB lookup to `/bin/echo 127.0.0.5 hostname<00>`, replacing 127.0.0.5 with other 127.0.0.x numbers.  Then add a `Host 127.0.0.5` to .ssh/config with the needed settings.  Brutal, but it gets the job done.
