### ISSUE TITLE
Always got alert like 'no backups of xxx have succeeded' even i deleted that host

### ISSUE THREAD

**Issue by wqbbs911** [backuppc/backuppc#141]
In recent months we always got alert mail like  'no backups of xxx have succeeded' for 3 hosts every day ,  even i deleted one host and other 2 host got success backup every day, any tools or logs can debug/disable it or really something wrong in configuration file,etc ?

software version: BackupPC-3.3.0-10.fc15.x86_64
platform: fedora 15

**Comment by craigbarratt** [comment]
Not sure what the reason is.  First, have you restarted BackupPC?  It should remove any old hosts from the status.pl file at startup.

The "no backups of xxx have succeeded" message happens is the backups file in that host's data directory doesn't have any entries.  Can you browse backups for those hosts?

If you want to debug this, you could add some debug statements to BackupPC_sendEmail.

**Comment by wqbbs911** [comment]
yes , restarted BackupPC , but still got such email every day even i removed one pc from backuppc:
{
Dear backuppc,

Your PC (XXXX) has never been successfully backed up by our
PC backup software.  PC backups should occur automatically
when your PC is connected to the network.  You should contact
computer support if:

  - Your PC has been regularly connected to the network, meaning
    there is some configuration or setup problem preventing
    backups from occurring.

  - You don't want your PC backed up and you want these email
    messages to stop.

Otherwise, please make sure your PC is connected to the network
next time you are in the office.

Regards,
BackupPC Genie
http://backuppc.sourceforge.net
}

and how to debug it in BackupPC_sendEmail ??
