### ISSUE TITLE
Feature Request: Storage Tiering

### ISSUE THREAD

**Issue by futureweb** [backuppc/backuppc#154]
Hello,

we are using BackupPC 3.3.0 for backing up dozens of Virtual Servers using BackupPC rsync implementation. Lot's of them are pretty big (>10-20 Millions of Small Files, >1TB) which results in Backup-Times up to 4-6 Days per Server which is not really acceptable! :-(
Backup Target is a 12 HDD RAID 5 running on DL380 Gen9 Server. This 12 HDD Raid is going to 100% IO when the Backups are running - so we think this is the bottleneck ... 
Would you consider adding some kind of Storage Tiering to BackupPC? 
So one could say - do the initial Backup to a smaller SSD Raid - and then deduplicate the Data in Background to the slower but bigger HDD Raid? Or somethink like this?
Don't see how else I could speed those Backups up ... :-/
(or do I overlook something here?)

Thank you, bye from sunny Austria
Andreas Schnederle-Wagner

**Comment by adamgoryachev** [comment]
On 28/9/17 22:01, Andreas Schnederle-Wagner wrote:
>
> Hello,
>
> we are using BackupPC 3.3.0 for backing up dozens of Virtual Servers 
> using BackupPC rsync implementation. Lot's of them are pretty big 
> (>10-20 Millions of Small Files, >1TB) which results in Backup-Times 
> up to 4-6 Days per Server which is not really acceptable! :-(
> Backup Target is a 12 HDD RAID 5 running on DL380 Gen9 Server. This 12 
> HDD Raid is going to 100% IO when the Backups are running - so we 
> think this is the bottleneck ...
> Would you consider adding some kind of Storage Tiering to BackupPC?
> So one could say - do the initial Backup to a smaller SSD Raid - and 
> then deduplicate the Data in Background to the slower but bigger HDD 
> Raid? Or somethink like this?
> Don't see how else I could speed those Backups up ... :-/
> (or do I overlook something here?)
>
> Thank you, bye from sunny Austria
> Andreas Schnederle-Wagner
>
> —
>

You would probably be better of using a SSD cache in your underlying 
storage layers. BPC doesn't "care" about filesystem or block devices, 
and probably shouldn't need to worry about all that complexity. I think 
there are two main caching systems, one is part of LVM and the second is 
a dedicated block device, both are part of the Linux kernel (AFAIK). I 
would suggest using one or the other, depending on your requirements, 
which will automatically cache the writes.

You should also ensure you have enough RAM on both the client and the 
BPC server, as you will want a *lot* of memory available for read 
caching the directories/metadata.

Finally, you might want to upgrade to BPC 4, I've found it works better 
for this type of use case, partly because it doesn't need to walk the 
entire client FS before starting the backup process, and also doesn't 
need as much RAM to store the full walk (both client and server side).

Oh, and you might also want to examine the IO on your RAID5. If you are 
doing a lot of RMW, then you should consider changing to a smaller chunk 
size. Also, check you have noatime or equivalent enabled for the BPC 
pool FS, as it will lead to a lot of unnecessary writes. Splitting into 
2 x RAID5 arrays with 6 drives each, and then combining using either 
linear or RAID0 will also improve performance (probably).
Also look where your swap partition is, make sure it isn't on the same 
RAID5 array, or any memory pressure will just make the situation even worse.

Look carefully at each bottleneck, and then see if you can improve that.

I hope that this helps a little...

Regards,
Adam

**Comment by craigbarratt** [comment]
In addition to Adam's suggestions, you might want to try BackupPC 4.x.  The rsync xfer method is significantly faster than 3.x.
