### ISSUE TITLE
Filenames get truncated after approx. 100 chars

### ISSUE THREAD

**Issue by jensd0e** [backuppc/backuppc#176]
Backing up with the default smb command:
> $smbClientPath \\$host\$shareName $I_option -U $userName -E -d 1 -c tarmode\ full -mSMB3 -Tc$X_option - $fileList

long filenames get truncated after 97-99 chars.

Tested on two setups:
1.) Server: Debian 8.10, BackupPC 4.1.5, smbclient 4.2.14, tar 1.27.1, Host: Windows Server 2012 R2
2.) VM Server: Debian 9.2, BackupPC 4.1.5, smbclient 4.5.12, tar 1.29, Host: Windows Server 2016

One can verify this by navigating to a file with a very long name (>=100 chars) in the web-frontend. The filename is truncated there. The file is also truncated after restoring.

**Comment by SpareSimian** [comment]
Filesystems have finite allowed path lengths. BackupPC stores files under their original paths appended to the path to the host's backup directory. On my system, that's /var/lib/BackupPC/pc/<hostname>. So that length of characters eats away at the number of allowed characters in the client's path names. Make sure you use a backup filesystem that has a very long allowed path length.  Alas, most filesystems limit the path length to 255 characters. 

https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

**Comment by jensd0e** [comment]
My file-system is ext3. I just tested with 'touch' to create some files: the limit seems to be 256 chars - but the path does not add to the limit. So this does not explain, what happens here.

Thanks for your help.

**Comment by SpareSimian** [comment]
Is the path truncated on-disk? If you navigate to /var/lib/BackupPC/pc/<hostname>/very-long-path, is it truncated there? (Ie. is it truncated before storing the backup, or after reading the backup from storage?) (I'm not seeing this with rsync backups.)

**Comment by craigbarratt** [comment]
I believe windows file systems are limited to path name lengths of 260 (see [https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx]).  So this is a limitation of smb (and therefore smbclient).

You could check with smbclient's command-line interface.

That link mentions you can get extended long file paths by prepending your share with "\\?\".  You might want to manually try that with smbclient's command-line interface.

**Comment by SpareSimian** [comment]
I just checked my backup and the longest path is 400 characters. Some research indicates that the Linux path length is 4096 characters, as set in a kernel header file.

**Comment by jensd0e** [comment]
@craigbarratt : thanks for the hint. I'll test it and report back.

**Comment by jensd0e** [comment]
Just tested with smbclient's command-line: A filename that is truncated in my backup, is displayed correctly in smb session (using 'dir' command). Using 'get', I can copy the file with full name.

Client: Windows 7 x64
Command: /usr/bin/smbclient \\\\win7\\Share  -U backupoperator -mSMB3

Any ideas?

**Comment by craigbarratt** [comment]
By default, tar headers only support 99 character file names.  GNU tar introduced an extension long ago that allowed long file names, which BackupPC supports and uses.

In looking at the source code for smbclient, it appears to use pax header formats for the tar file, which use a different mechanism to support longer file names.  So unfortunately it appears that the issue is the long file format produced by smbclient isn't supported by BackupPC.  I don't know if or when smbclient changed the tar format from GNU to pax.

There are two choices - modify smbclient to support GNU tar long file names, or support the pax format headers in BackupPC.

**Comment by craigbarratt** [comment]
Ok, I implemented pax support to BackupPC_tarCreate, although I haven't tested it.

Would you be willing to test this version?  Can I email you the code?

**Comment by jensd0e** [comment]
YES, please! I'd love to test it! :-) You can send it to bpc@innovation.uni-bremen.de

**Comment by craigbarratt** [comment]
Ok, I sent you the test version of BackupPC_tarExtract.

**Comment by jensd0e** [comment]
The patch you send works as desired. Long filenames get backed now. :-)
Thank you very much!

**Comment by craigbarratt** [comment]
Thanks for confirming, and thanks for helping debug the issue.

I pushed the code with commit 85675ef.
