### ISSUE TITLE
I entered: /usr/share/BackupPC/bin/BackupPC_restore 

### ISSUE THREAD

**Issue by avasptech** [backuppc/backuppc#242]
I entered: /usr/share/BackupPC/bin/BackupPC_restore 10.x.x.x 10.x.x.x test.tar. And got the error
restore failed: couldn't do /var/lib/BackupPC//pc/10.x.x.x/test.tar: No such file or directory

I'm looking forward to hear from anybody with a clue to fix this problem!

Best regards,
Mohd. Ali

**Comment by craigbarratt** [comment]
BackupPC_restore isn't meant to be a user command.  It's argument is a file that contains a small perl data file with all the restore information.  You can look in the CGI restore code to see how this file is constructed if you do want to use BackupPC_restore manually.  Otherwise, there are command-line restore options discussed in the documentation.

Also, please send user questions to the BackupPC user list.  Git issues are for reporting bugs.
