### ISSUE TITLE
rsync direct restore of a single file removes all other files in directory

### ISSUE THREAD

**Issue by marcquark** [backuppc/backuppc#356]
On BackupPC version 4.3.0, using direct restore and rsync for a single file within a directory removes all other existing files in the destination. This is not intuitive and could cause serious damage, e.g. if you want to restore a single file in a share after accidental deletion. You would expect that the file is simply restored, but what you really get is you wipe out the whole share and just that one restored file remains.

The reason for this is that $RsyncRestoreArgs contains "--delete", which was there by default, at least on my installation. I can't think of a scenario where such behaviour would be wanted. During backup, sure, i don't want old and deleted stuff to bloat my storage pool. But during restore i don't think --delete makes sense in most common scenarios.

In the rare case that one has messed up a whole folder and wants to restore the backup state (like a snapshot), there are two easy workarounds if --delete is not there by default:
- Add --delete to $RsyncRestoreArgs temporarily
- Delete the folder on the host before restoring it

**Comment by marcquark** [comment]
https://github.com/backuppc/backuppc/blob/master/conf/config.pl#L1389
This is the line in question, imho it should be removed

**Comment by craigbarratt** [comment]
Excellent point.  I pushed a change 6659184 to remove `--delete` from `$Conf{RsyncRestoreArgs}`.

**Comment by discoverSlow** [comment]
Consider  a setting where a true subset of items in a directory is marked for backup, like here: The directory D contains the items (files or directories)  { IT_1,  IT_2,  IT_3,  it_4,  it_5} ,  where IT_1 and  IT_2 and IT_3 are marked for backup while  it_4 and it_5 are not.
As long as we select for restore any true subset of the backup items - e.g. restore(IT_2, IT_3)  - BackupPC  treats the restore object as a set of items; BackupPC output:

Original   file/dir | Will be   restored to
-- | --
johannix:/home/peter/D/IT_2 | johannix:/home/peter/D/IT_2
johannix:/home/peter/D/IT_3 | johannix:/home/peter/D/IT_3

If we  restore(IT_1, IT_2, IT_3), which is the whole set of backup items, backuppc treats the restore object as directory D, rather than the set  { IT_1, IT_2, IT_3 } , as if assuming that this set represents the whole contents of D. BackupPC output:

Original   file/dir | Will be   restored to
-- | --
johannix:/home/peter/D/ | johannix:/home/peter/D/

The  --delete  option in the restore-rsync-command makes the restore action delete items it_4 and it_5 from directory D.  While it is true, that also in this case removing the --delete  option is an effective cure, one could argue that the root cause for the deletion problem is identifying the backup set (which is a true subset of D) with the full content of D. W/o this identification the --delete  option would not hurt.
Note that the error mentioned in the issue title is just a special case of the general scenario described here: the backup-set is a singleton;  restoring its single element means restoring the whole set of backup items.
My writing is just meant as a comment that removing the --delete  option from the restore-sync-command not only repairs the issue indicated in the issue title but also repairs the more general error scenario I described. 
Moreover, wouldn’t it be perhaps safer (and conceptually more clean)  to not identify the set of backup-items in a directory D with D’s  whole content, if that backup set is a true subset of D ?

**Comment by marcquark** [comment]
> If we restore [...] backuppc treats the restore object as directory D, [...] as if assuming that this set represents the whole contents of D [...]

That's because it effectively _is_ the whole content of D.

>[...] While it is true, that also in this case removing the --delete option is an effective cure, one could argue that the root cause for the deletion problem is identifying the backup set (which is a true subset of D) with the full content of D. W/o this identification the --delete option would not hurt.

You'd also have to do this recursively to identify every single item that needs to be restored. In other words: You would reimplement the logic of rsync. Why do that when you can simply omit the unnecessary parameter?

> Note that the error mentioned in the issue title is just a special case of the general scenario described here: the backup-set is a singleton; restoring its single element means restoring the whole set of backup items.
> My writing is just meant as a comment that removing the --delete option from the restore-sync-command not only repairs the issue indicated in the issue title but also repairs the more general error scenario I described.
> Moreover, wouldn’t it be perhaps safer (and conceptually more clean) to not identify the set of backup-items in a directory D with D’s whole content, if that backup set is a true subset of D ?

While my title and description focus on restoring a single file, removing that parameter effectively resolves a broader range of issues, that is correct.
Your example neglects a lot of cases though. I already mentioned recursion. What about files that do not exist in the backup folder, but do exist on a host - not because they weren't selected for backup but simply because they were created after the last backup? What about the same scenario in subfolders (recursion again)? And so on... No matter how you spin it and what you try to implement, it would most likely just become a buggy version of rsync.
And all that just to generate commands that then call rsync with --delete, instead of omitting the parameter and letting rsync do the job it has been designed to do? No point really...

**Comment by discoverSlow** [comment]
Thanks for the very quick answer.

First of all, I do not object against removing the --delete option from $RsyncRestoreArgs, I think it is absolutele the right thing to do. Maybe I had not made that clear enough.

        as if assuming that this set represents the whole contents of D [...]

> That's because it effectively is the whole content of D. 

In the example **D = { IT_1, IT_2, IT_3, it_4, it_5}**  and the set of items marked for backup (_backup set_) is **{IT_1, IT_2, IT_3}** so the _backup set_ is a true subset of D, it is _not_ the whole content of D. And it plays of course no role, whether the items not in the backup set  (it_4 and it_5 in the example)  had been added after the backup took place or had existed before.

> You'd also have to do this recursively to identify every single item that needs to be restored. 

No. Simply let backuppc _always_ restore exactly the set of items the user had specified in the restore action (which is the case when the user restores a true subset of the backup set)  and let backuppc **never** identify the _restore set_ with D,  because that kind of "optimisation" could be correct only incidentally.

**Comment by marcquark** [comment]
> In the example **D = { IT_1, IT_2, IT_3, it_4, it_5}** and the set of items marked for backup (_backup set_) is **{IT_1, IT_2, IT_3}** so the _backup set_ is a true subset of D, it is _not_ the whole content of D. And it plays of course no role, whether the items not in the backup set (it_4 and it_5 in the example) had been added after the backup took place or had existed before.

You're overcomplicating things. There are only two sets of data that are relevant here: The Backup you're trying to restore (in your terms: "the backup set"), and the live data on the target host (in your terms "D"). There is technically _no_ difference between a file/folder excluded from the backup and a file/folder that was simply not backed up yet.

> No. Simply let backuppc _always_ restore exactly the set of items the user had specified in the restore action (which is the case when the user restores a true subset of the backup set) and let backuppc **never** identify the _restore set_ with D, because that kind of "optimisation" could be correct only incidentally.

As already pointed out, that's simply a complicated way of phrasing "let rsync do the job". You're still completely ignoring recursion in your thought process. What about a file F_1 below IT_2 that hasn't been backed up yet? In your logic, that file would not be part of "the backup set" and BackupPC should detect that and then attempt to restore all individual items except for F_1. If you leave out recursion and call rsync with --delete, you will unintentionally delete files. Don't believe me? Do this:

1. Add --delete back to your RsyncRestoreArgs
2. Create an example scenario like you described and take a backup
3. Define your "true subset of the backup set" as the "restore set"
4. On the backed up host, go to one of the folders that is in the restore set and create a file
5. Restore your restore set
6. See if the file is still there

I can only repeat myself: If you apply your own logic correctly (that includes applying it recursively), you'll do exactly what rsync does already. To be honest with you, i don't think this discussion adds any value and will not lead to any useful output, sorry. Hence this is going to be my last reply.

If you think BackupPC is doing something fundamentally wrong, submit a PR i guess?

**Comment by discoverSlow** [comment]
Obviously a continued misunderstanding between us, maybe my assumption about how BPC works is wrong, maybe you don't see my point..., I don't know.
 I agree to discontinue our discussion and rather opened   https://github.com/backuppc/backuppc/issues/399 
Let us see, what others say.
