### ISSUE TITLE
Fix nightly pool statistics updates

### ISSUE THREAD

**Issue by akobel** [backuppc/backuppc#56]
Stumbled across this via the build files for Sébastien Luttringer's [package for Arch Linux](https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/backuppc) (I have to admit that I didn't confirm the issue on an unpatched BackupPC, but I think it's worth mentioning anyway, because _someone_ did spend time and thoughts earlier on.)

There seems to be a problem in updating the pool statistics, according to [this mailing list post](https://sourceforge.net/p/backuppc/mailman/message/30091324/). There is a proposed fix from the Debian package maintainers mentioned, which has been updated to apply to v4.0 by Sébastien in [his patch](https://git.archlinux.org/svntogit/community.git/tree/trunk/01-fix-FS%2332642.patch?h=packages/backuppc) for the Arch package (the problematic code moved from `lib/BackupPC/Lib.pm` to `lib/BackupPC/DirOps.pm`).

**Comment by craigbarratt** [comment]
Thanks for pointing that out.

It's fixed in 3.3.0+ back in 2013 by having better detection that
IO::Dirent actually works.  See
https://github.com/backuppc/backuppc/commit/be59c3ae4f452f89b08a3e66bf10ba035fc9c02d
(search for IODirentOk).

However, I noticed that not all those same checks made it into 4.0 (it was
forked before that 3.x fix), so I need to update 4.0 with the additional
checks that IO::Dirent works correctly before enabling it.

Craig

**Comment by craigbarratt** [comment]
Pushed fix that better confirms IO::Dirent works before enabling it.
